name: Trigger auto deployment for ethivault-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ethivault-dev-AutoDeployTrigger-2dc655fb-e6d1-4f2c-9fcb-15e4958d56e8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ETHIVAULTDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ETHIVAULTDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ETHIVAULTDEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: iverseregistry.azurecr.io
          registryUsername: ${{ secrets.ETHIVAULTDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ETHIVAULTDEV_REGISTRY_PASSWORD }}
          containerAppName: ethivault-dev
          resourceGroup: iverse
          imageToBuild: iverseregistry.azurecr.io/ethivault-dev:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


